# Generated by Django 2.1.1 on 2018-10-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogapp', '0002_auto_20181025_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='membresia',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='clase',
            name='cupo',
            field=models.IntegerField(default=0),
        ),
    ]
